<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="employeemanagerv1-0"
    errors="0" failures="1" hostname="" id="" package="employeemanagerv1-0" skipped="0"
    tests="1" time="0.4590" timestamp="">
  
    <testcase name="ID" classname="employeemanagerv1-0" time="0.4590" assertions="1">  <failure message="Failed [ok]: (The ID (-4) is a positive number.) - expected [0;32m&#34;true&#34;[0m but got: [0;31m&#34;false&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Owner\DevMtn\practiceAutomation\ClassPractice\tests\employeemanagerv1-0.js:6:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

    <failure message="    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Owner\DevMtn\practiceAutomation\ClassPractice\tests\employeemanagerv1-0.js:6:14)">    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
